FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o /app/publish

# -----------------------
# RUNTIME IMAGE
# -----------------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

# HTTP only — no HTTPS
ENV ASPNETCORE_URLS="http://+:5001"

EXPOSE 5001

ENTRYPOINT ["dotnet", "Grievance.API.dll"]
